# Generated by Django 4.2 on 2023-05-14 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_jobs_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicationDate',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
